// Environment variables configuration
export const config = {
  GITHUB_TOKEN: __GITHUB_TOKEN__,
  INSTAGRAM_ACCESS_TOKEN: __INSTAGRAM_ACCESS_TOKEN__,
  INSTAGRAM_BUSINESS_ACCOUNT_ID: __INSTAGRAM_BUSINESS_ACCOUNT_ID__,
  SLACK_WEBHOOK_URL: __SLACK_WEBHOOK_URL__,
  INSTAGRAM_USERNAME: __INSTAGRAM_USERNAME__,
};
