// Static environment variable defaults
const ENV = {
  VITE_GITHUB_TOKEN: '__VITE_GITHUB_TOKEN_PLACEHOLDER__',
  VITE_INSTAGRAM_ACCESS_TOKEN: '__VITE_INSTAGRAM_ACCESS_TOKEN_PLACEHOLDER__',
  VITE_INSTAGRAM_BUSINESS_ACCOUNT_ID: '__VITE_INSTAGRAM_BUSINESS_ACCOUNT_ID_PLACEHOLDER__',
  ADMIN_TOKEN: '__ADMIN_TOKEN_PLACEHOLDER__',
};

export default ENV;
