// Static environment variable defaults
const ENV = {
  GITHUB_TOKEN: '__GITHUB_TOKEN_PLACEHOLDER__',
  INSTAGRAM_ACCESS_TOKEN: '__INSTAGRAM_ACCESS_TOKEN_PLACEHOLDER__',
  INSTAGRAM_BUSINESS_ACCOUNT_ID: '__INSTAGRAM_BUSINESS_ACCOUNT_ID_PLACEHOLDER__',
  SLACK_WEBHOOK_URL: '__SLACK_WEBHOOK_URL_PLACEHOLDER__',
  INSTAGRAM_USERNAME: '__INSTAGRAM_USERNAME_PLACEHOLDER__',
};

export default ENV;
