#.github/workflows/generate-and-post.yml
name: Generate and Post Gig Guide

on:
  schedule:
    - cron: '35 7 * * *' # 7:35 AM daily
  workflow_dispatch: # Allow manual triggers

jobs:
  generate-images:
    runs-on: ubuntu-latest
    permissions: # Add permissions for deleting files
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start React app (if needed)
        run: npm run dev & # Start the React app in the background (if you need it for image generation)

      - name: Delete temporary images (BEFORE generating new ones)
        run: |
          find temp-images/ -mindepth 1 -not -name "README.md" -delete # Keep README.md
          mkdir -p temp-images
          chmod 777 temp-images # Optional, but good practice

      - name: Generate images
        run: node generateImages.js

      - name: Upload images to Imgur (or GitHub in your case)
        run: |
          # Add Imgur/GitHub upload logic here
          echo "Uploading images..."

      - name: Post to Instagram
        run: |
          # Add Instagram posting logic here
          echo "Posting to Instagram..."

      - name: Send Slack notification
        run: |
          # Add Slack notification logic here
          echo "Sending Slack notification..."